// Code generated by protoc-gen-go.
// source: naming.proto
// DO NOT EDIT!

/*
Package naming is a generated protocol buffer package.

It is generated from these files:
	naming.proto

It has these top-level messages:
	AOR
	BindRequest
	BindResponse
	LookupRequest
	LookupResponse
	LookupManyRequest
	LookupManyResponse
	LookupAllRequest
	LookupAllResponse
*/
package naming

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type AOR struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Id   string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *AOR) Reset()         { *m = AOR{} }
func (m *AOR) String() string { return proto.CompactTextString(m) }
func (*AOR) ProtoMessage()    {}

type BindRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	Aor         *AOR   `protobuf:"bytes,2,opt,name=aor" json:"aor,omitempty"`
}

func (m *BindRequest) Reset()         { *m = BindRequest{} }
func (m *BindRequest) String() string { return proto.CompactTextString(m) }
func (*BindRequest) ProtoMessage()    {}

func (m *BindRequest) GetAor() *AOR {
	if m != nil {
		return m.Aor
	}
	return nil
}

type BindResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *BindResponse) Reset()         { *m = BindResponse{} }
func (m *BindResponse) String() string { return proto.CompactTextString(m) }
func (*BindResponse) ProtoMessage()    {}

type LookupRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}

type LookupResponse struct {
	Aor   *AOR   `protobuf:"bytes,1,opt,name=aor" json:"aor,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *LookupResponse) Reset()         { *m = LookupResponse{} }
func (m *LookupResponse) String() string { return proto.CompactTextString(m) }
func (*LookupResponse) ProtoMessage()    {}

func (m *LookupResponse) GetAor() *AOR {
	if m != nil {
		return m.Aor
	}
	return nil
}

type LookupManyRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	NumberOfAor uint32 `protobuf:"varint,2,opt,name=numberOfAor" json:"numberOfAor,omitempty"`
}

func (m *LookupManyRequest) Reset()         { *m = LookupManyRequest{} }
func (m *LookupManyRequest) String() string { return proto.CompactTextString(m) }
func (*LookupManyRequest) ProtoMessage()    {}

type LookupManyResponse struct {
	AorList []*AOR `protobuf:"bytes,1,rep,name=aorList" json:"aorList,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *LookupManyResponse) Reset()         { *m = LookupManyResponse{} }
func (m *LookupManyResponse) String() string { return proto.CompactTextString(m) }
func (*LookupManyResponse) ProtoMessage()    {}

func (m *LookupManyResponse) GetAorList() []*AOR {
	if m != nil {
		return m.AorList
	}
	return nil
}

type LookupAllRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *LookupAllRequest) Reset()         { *m = LookupAllRequest{} }
func (m *LookupAllRequest) String() string { return proto.CompactTextString(m) }
func (*LookupAllRequest) ProtoMessage()    {}

type LookupAllResponse struct {
	AorList []*AOR `protobuf:"bytes,1,rep,name=aorList" json:"aorList,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *LookupAllResponse) Reset()         { *m = LookupAllResponse{} }
func (m *LookupAllResponse) String() string { return proto.CompactTextString(m) }
func (*LookupAllResponse) ProtoMessage()    {}

func (m *LookupAllResponse) GetAorList() []*AOR {
	if m != nil {
		return m.AorList
	}
	return nil
}

func init() {
}
