// Code generated by protoc-gen-go.
// source: naming.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	naming.proto

It has these top-level messages:
	AOR
	NamingServiceBindRequest
	NamingServiceBindResponse
	NamingServiceLookupRequest
	NamingServiceLookupResponse
	NamingServiceLookupManyRequest
	NamingServiceLookupManyResponse
	NamingServiceLookupAllRequest
	NamingServiceLookupAllResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

type AOR struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Id   string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *AOR) Reset()         { *m = AOR{} }
func (m *AOR) String() string { return proto1.CompactTextString(m) }
func (*AOR) ProtoMessage()    {}

type NamingServiceBindRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	Aor         *AOR   `protobuf:"bytes,2,opt,name=aor" json:"aor,omitempty"`
}

func (m *NamingServiceBindRequest) Reset()         { *m = NamingServiceBindRequest{} }
func (m *NamingServiceBindRequest) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceBindRequest) ProtoMessage()    {}

func (m *NamingServiceBindRequest) GetAor() *AOR {
	if m != nil {
		return m.Aor
	}
	return nil
}

type NamingServiceBindResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *NamingServiceBindResponse) Reset()         { *m = NamingServiceBindResponse{} }
func (m *NamingServiceBindResponse) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceBindResponse) ProtoMessage()    {}

type NamingServiceLookupRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *NamingServiceLookupRequest) Reset()         { *m = NamingServiceLookupRequest{} }
func (m *NamingServiceLookupRequest) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceLookupRequest) ProtoMessage()    {}

type NamingServiceLookupResponse struct {
	Aor   *AOR   `protobuf:"bytes,1,opt,name=aor" json:"aor,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *NamingServiceLookupResponse) Reset()         { *m = NamingServiceLookupResponse{} }
func (m *NamingServiceLookupResponse) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceLookupResponse) ProtoMessage()    {}

func (m *NamingServiceLookupResponse) GetAor() *AOR {
	if m != nil {
		return m.Aor
	}
	return nil
}

type NamingServiceLookupManyRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	NumberOfAor uint32 `protobuf:"varint,2,opt,name=numberOfAor" json:"numberOfAor,omitempty"`
}

func (m *NamingServiceLookupManyRequest) Reset()         { *m = NamingServiceLookupManyRequest{} }
func (m *NamingServiceLookupManyRequest) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceLookupManyRequest) ProtoMessage()    {}

type NamingServiceLookupManyResponse struct {
	AorList []*AOR `protobuf:"bytes,1,rep,name=aorList" json:"aorList,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *NamingServiceLookupManyResponse) Reset()         { *m = NamingServiceLookupManyResponse{} }
func (m *NamingServiceLookupManyResponse) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceLookupManyResponse) ProtoMessage()    {}

func (m *NamingServiceLookupManyResponse) GetAorList() []*AOR {
	if m != nil {
		return m.AorList
	}
	return nil
}

type NamingServiceLookupAllRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *NamingServiceLookupAllRequest) Reset()         { *m = NamingServiceLookupAllRequest{} }
func (m *NamingServiceLookupAllRequest) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceLookupAllRequest) ProtoMessage()    {}

type NamingServiceLookupAllResponse struct {
	AorList []*AOR `protobuf:"bytes,1,rep,name=aorList" json:"aorList,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *NamingServiceLookupAllResponse) Reset()         { *m = NamingServiceLookupAllResponse{} }
func (m *NamingServiceLookupAllResponse) String() string { return proto1.CompactTextString(m) }
func (*NamingServiceLookupAllResponse) ProtoMessage()    {}

func (m *NamingServiceLookupAllResponse) GetAorList() []*AOR {
	if m != nil {
		return m.AorList
	}
	return nil
}

func init() {
}
