// Code generated by protoc-gen-go.
// source: storage_object.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	storage_object.proto

It has these top-level messages:
	StorageObjectUploadRequest
	StorageObjectUploadResponse
	StorageObjectDownloadRequest
	StorageObjectDownloadResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

type StorageObjectUploadRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path" json:"file_path,omitempty"`
	Start    int64  `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Bytes    []byte `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (m *StorageObjectUploadRequest) Reset()         { *m = StorageObjectUploadRequest{} }
func (m *StorageObjectUploadRequest) String() string { return proto1.CompactTextString(m) }
func (*StorageObjectUploadRequest) ProtoMessage()    {}

type StorageObjectUploadResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *StorageObjectUploadResponse) Reset()         { *m = StorageObjectUploadResponse{} }
func (m *StorageObjectUploadResponse) String() string { return proto1.CompactTextString(m) }
func (*StorageObjectUploadResponse) ProtoMessage()    {}

type StorageObjectDownloadRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path" json:"file_path,omitempty"`
	Start    int64  `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Offset   int32  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *StorageObjectDownloadRequest) Reset()         { *m = StorageObjectDownloadRequest{} }
func (m *StorageObjectDownloadRequest) String() string { return proto1.CompactTextString(m) }
func (*StorageObjectDownloadRequest) ProtoMessage()    {}

type StorageObjectDownloadResponse struct {
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *StorageObjectDownloadResponse) Reset()         { *m = StorageObjectDownloadResponse{} }
func (m *StorageObjectDownloadResponse) String() string { return proto1.CompactTextString(m) }
func (*StorageObjectDownloadResponse) ProtoMessage()    {}

func init() {
}
