// Code generated by protoc-gen-go.
// source: storage_object.proto
// DO NOT EDIT!

/*
Package storage_object is a generated protocol buffer package.

It is generated from these files:
	storage_object.proto

It has these top-level messages:
	UploadRequest
	UploadResponse
	DownloadRequest
	DownloadResponse
*/
package storage_object

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type UploadRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path" json:"file_path,omitempty"`
	Start    int64  `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Bytes    []byte `protobuf:"bytes,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}

type UploadResponse struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *UploadResponse) Reset()         { *m = UploadResponse{} }
func (m *UploadResponse) String() string { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()    {}

type DownloadRequest struct {
	FilePath string `protobuf:"bytes,1,opt,name=file_path" json:"file_path,omitempty"`
	Start    int64  `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	Offset   int32  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *DownloadRequest) Reset()         { *m = DownloadRequest{} }
func (m *DownloadRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadRequest) ProtoMessage()    {}

type DownloadResponse struct {
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *DownloadResponse) Reset()         { *m = DownloadResponse{} }
func (m *DownloadResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadResponse) ProtoMessage()    {}

func init() {
}
